export const DEFAULT_SYMPTOMS = [
  "fatigue",
  "hair_fall",
  "weakness",
  "mood_fluctuations",
  "irregular_cycles",
  "weight_gain",
  "skin_issues",
  "heavy_bleeding",
  "bloating",
  "brain_fog",
  "hot_flashes",
  "night_sweats",
  "poor_sleep",
];

export const PHYSICAL_SYMPTOMS = [
  "fatigue",
  "hair_fall",
  "weakness",
  "irregular_cycles",
  "no_period",
  "weight_gain",
  "weight_loss",
  "skin_issues",
  "acne",
  "heavy_bleeding",
  "menstrual_cramps",
  "pelvic_pain",
  "pelvic_pressure",
  "bloating",
  "hot_flashes",
  "night_sweats",
  "cold_intolerance",
  "heat_intolerance",
  "brain_fog",
  "appetite_changes",
  "food_cravings",
  "cravings",
  "brittle_nails",
  "breast_tenderness",
  "headaches",
  "palpitations",
  "dry_skin",
  "constipation",
  "muscle_cramps",
  "excessive_sweating",
  "tremor",
  "excess_hair",
  "thinning_hair",
  "abdominal_weight",
  "sugar_cravings",
  "shortness_breath",
  "pale_skin",
  "pica_cravings",
  "slow_heart_rate",
  "temperature_sensitivity",
  "acanthosis_nigricans",
  "skin_tags",
];

export const MEDICAL_HISTORY = [
  "thyroid_swelling",
  "family_thyroid",
  "thyroid_medication",
  "missed_periods",
  "family_pcos",
  "spoon_nails",
  "tea_coffee_meals",
  "anemia_diagnosed",
  "iron_rich_food",
];

export const EMOTIONAL_SYMPTOMS = [
  "mood_fluctuations",
  "irritability",
  "anxiety",
  "depression",
  "stress",
  "libido_changes",
];

export const BEHAVIORAL_INDICATORS = [
  "poor_sleep",
  "low_sunlight_exposure",
  "sedentary_lifestyle",
  "high_caffeine",
  "irregular_meals",
];

export const FREQUENCY_OPTIONS = ["none", "rarely", "sometimes", "often", "always"];
